spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers:
      - localhost:9092
    producer:
      bootstrap-servers:
      - localhost:9092

server:
  port: 8085
