server:
  port: 8085

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
    instances:
      review:
        baseConfig: default

springdoc:
  swagger-ui:
    path: /api/reviews/swagger-ui.html

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://recofit-db.caxwmkvaba6j.ap-northeast-2.rds.amazonaws.com/review
    username: root
    password: 2!qkfzlfldk;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      bootstrap-servers:
      - ec2-3-39-234-99.ap-northeast-2.compute.amazonaws.com:9092
      # - b-1.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-3.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers:
      - ec2-3-39-234-99.ap-northeast-2.compute.amazonaws.com:9092
      # - b-1.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-3.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
