server:
  port: 8085

---

# spring:
#   datasource:
#     url: jdbc:h2:mem:review
#   jpa:
#     show-sql: true

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://recofit-db.caxwmkvaba6j.ap-northeast-2.rds.amazonaws.com/review
    username: root
    password: 2!qkfzlfldk;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      bootstrap-servers:
      - b-1.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-3.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092
    producer:
      bootstrap-servers:
      - b-1.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-3.recofit.bqx97j.c4.kafka.ap-northeast-2.amazonaws.com:9092
  # config:
    # activate:
    #   on-profile: prd
